from __future__ import annotations

from enum import Enum


class AuditStatus(str, Enum):
    CREATED = "CREATED"
    COLLECTING = "COLLECTING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AuditType(str, Enum):
    BASELINE_ENGINEERING = "BASELINE_ENGINEERING"
    RELEASE_READINESS = "RELEASE_READINESS"
    NON_REGRESSION = "NON_REGRESSION"
    SECURITY = "SECURITY"
    ARCHITECTURE = "ARCHITECTURE"
    PERFORMANCE = "PERFORMANCE"
    UI_DATA_INTEGRITY = "UI_DATA_INTEGRITY"
    EXTERNAL_REVIEW = "EXTERNAL_REVIEW"


class AuditProvider(str, Enum):
    NONE = "NONE"
    CODEX = "CODEX"
    OPENAI = "OPENAI"
    SONARQUBE = "SONARQUBE"
    SEMGREP = "SEMGREP"
    CODEQL = "CODEQL"
    EXTERNAL = "EXTERNAL"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class RecommendationCategory(str, Enum):
    BLOCKER = "BLOCKER"
    RC2_TECHNICAL_DEBT = "RC2_TECHNICAL_DEBT"
    OPTIMIZATION = "OPTIMIZATION"
    OBSERVATION = "OBSERVATION"


class FindingDomain(str, Enum):
    ARCHITECTURE = "ARCHITECTURE"
    SECURITY = "SECURITY"
    PERFORMANCE = "PERFORMANCE"
    MAINTAINABILITY = "MAINTAINABILITY"
    TESTING = "TESTING"
    DOCUMENTATION = "DOCUMENTATION"
    OBSERVABILITY = "OBSERVABILITY"
    GOVERNANCE = "GOVERNANCE"
    FRONTEND = "FRONTEND"
    BACKEND = "BACKEND"
    DATA_INTEGRITY = "DATA_INTEGRITY"
    DEPENDENCIES = "DEPENDENCIES"
    CI_CD = "CI_CD"
    OTHER = "OTHER"


class ArtifactRole(str, Enum):
    RELEASE_GATE = "RELEASE_GATE"
    BASELINE_POINTER = "BASELINE_POINTER"
    BASELINE_MANIFEST = "BASELINE_MANIFEST"
    MASTER_DOCUMENT = "MASTER_DOCUMENT"
    MASTER_STATUS = "MASTER_STATUS"
    CERTIFICATION = "CERTIFICATION"
    GOVERNANCE = "GOVERNANCE"
    SOURCE_INVENTORY = "SOURCE_INVENTORY"
    ARCHITECTURE_DOCUMENT = "ARCHITECTURE_DOCUMENT"
    ENGINEERING_CONSTITUTION = "ENGINEERING_CONSTITUTION"
    AUDIT_INSTRUCTION = "AUDIT_INSTRUCTION"
    OTHER = "OTHER"
